env:
  browser: true
  es6: true
extends:
  - 'vue'
  - 'airbnb-base'
  - 'eslint:recommended'
plugins:
  - import
  - vue
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
    - CallExpression:
        arguments: 1
  semi:
    - error
    - never
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  prefer-const:
    - warn
  no-console:
    - error
    - allow:
      - warn
      - error
  no-unused-vars:
    - warn
  no-new:
    - off
